In [3]:
import numpy as np
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [8]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [10]:
a1.dtype

dtype('int32')

In [11]:
a2.dtype

dtype('float64')

In [12]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [13]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.array([1,2]+[3,4])

array([1, 2, 3, 4])

In [20]:
np.array([1,2]*2+[3,4]*10)

array([1, 2, 1, 2, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4,
       3, 4])

In [17]:
np.array([1,2])+np.array([3,4])

array([4, 6])

In [21]:
np.array([1,2])*2+np.array([3,4])*10

array([32, 44])

In [22]:
#범위를 지정해 배열 생성
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [23]:
#범위를 지정해 배열 생성
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#범위를 지정해 배열 생성
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [9]:
b2 = np.arange(5)
b2.shape

(5, 1)

In [15]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.linspace(0, np.pi, 20 )

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
#단위 행렬
np.eye(3)*(-1)

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]])

In [26]:
#b : boolean
#i : int
#u : abs(int)
#f : float
#c : 복소수

np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [31]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
print(str_a1.dtype)
num_a1 = str_a1.astype(float)
print(num_a1)
print(num_a1.dtype)

<U5
[1.567 0.123 5.123 9.    8.   ]
float64


In [32]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [34]:
np.random.rand(2,3)

array([[0.6064823 , 0.87422202, 0.70450399],
       [0.11078979, 0.68413568, 0.94019521]])

In [35]:
np.random.rand()

0.04848547367138367

In [140]:
np.random.rand(2,3,4)

array([[[0.45369023, 0.17749785, 0.55455917, 0.84350319],
        [0.69552284, 0.5020849 , 0.45538847, 0.02058062],
        [0.09607884, 0.8309592 , 0.27997155, 0.86272586]],

       [[0.64132838, 0.40598991, 0.63047155, 0.74833285],
        [0.43740801, 0.64545822, 0.40785478, 0.38498258],
        [0.76598202, 0.6887194 , 0.66112334, 0.14395327]]])

In [141]:
np.random.randn(2,3,4) #표준정규분포를 따르는 난수 생성

array([[[ 0.88869531,  0.78401593, -1.27666811, -0.73923933],
        [ 0.28051449, -1.00489402, -1.14232248,  0.3890855 ],
        [ 1.2187565 , -1.12981355,  0.5686886 , -1.18002838]],

       [[-1.27293418,  0.23792771, -0.1496806 , -1.45220321],
        [ 0.61129736,  0.35909132, -0.57369115, -1.04216752],
        [ 2.08705558, -0.03322346, -0.45350686, -1.19988274]]])

In [37]:
np.random.randint(10, size=(3, 4))

array([[4, 0, 5, 2],
       [1, 4, 8, 7],
       [7, 0, 4, 8]])

In [134]:
np.random.randint(20, 30, size=(15,15))

array([[29, 27, 25, 28, 21, 24, 24, 29, 23, 21, 24, 22, 27, 26, 22],
       [24, 26, 24, 23, 29, 28, 22, 20, 26, 24, 21, 26, 22, 27, 26],
       [23, 28, 22, 24, 22, 24, 20, 24, 26, 23, 20, 29, 27, 24, 28],
       [25, 21, 20, 25, 23, 25, 27, 28, 29, 26, 29, 23, 21, 29, 24],
       [21, 29, 23, 27, 24, 25, 25, 27, 25, 28, 25, 25, 29, 21, 20],
       [21, 27, 23, 25, 23, 27, 25, 25, 25, 25, 26, 21, 26, 22, 23],
       [22, 22, 20, 21, 28, 29, 26, 28, 24, 25, 29, 28, 27, 27, 22],
       [22, 28, 22, 29, 20, 21, 29, 29, 25, 20, 27, 22, 24, 29, 25],
       [21, 25, 21, 25, 28, 29, 21, 26, 25, 27, 23, 20, 20, 28, 21],
       [26, 22, 22, 22, 23, 24, 24, 22, 29, 26, 23, 20, 24, 23, 22],
       [21, 25, 22, 22, 21, 28, 20, 21, 28, 22, 28, 22, 28, 24, 27],
       [25, 21, 22, 20, 20, 20, 29, 27, 27, 29, 27, 23, 20, 26, 28],
       [23, 23, 24, 21, 26, 25, 29, 23, 27, 20, 22, 26, 29, 29, 20],
       [23, 20, 21, 22, 27, 26, 23, 25, 26, 29, 28, 27, 24, 27, 25],
       [21, 28, 20, 20, 20, 28, 22

In [135]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
arr1 + arr2

array([11, 22, 33, 44])

In [136]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [137]:
arr2 * 2

array([2, 4, 6, 8])

In [138]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [139]:
arr1 * arr2 #배열의 곱

array([ 10,  40,  90, 160])

In [142]:
arr1 / arr2 #배열의 나누기

array([10., 10., 10., 10.])

In [143]:
arr1 / (arr2 ** 2) #배열의 나누기

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [145]:
arr1 > 20

array([False, False,  True,  True])

In [147]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [148]:
[arr3.sum(), arr3.mean()] #합, 평균

[10, 2.0]

In [151]:
[arr3.std(), arr3.var()] #분산, 표준편차

[1.4142135623730951, 2.0]

In [153]:
[arr3.min(), arr3.max()] #최소, 최대 값

[0, 4]

In [154]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [155]:
arr4.cumsum() # 누적합

array([ 1,  3,  6, 10], dtype=int32)

In [156]:
arr4.cumprod() # 누적곱

array([ 1,  2,  6, 24], dtype=int32)

In [168]:
#임의의 이차원 배열
arr = np.arange(12).reshape(4,3)
print(arr)
for ar in  arr : 
    print(ar.mean())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
1.0
4.0
7.0
10.0


In [182]:
#####################################################################################행렬 연산

In [193]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [179]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [180]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [181]:
#행렬 곱
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [195]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [196]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [197]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [198]:
np.linalg.det(A)

-2.0

In [229]:
W = np.array([0.9,0.3,0.4,0.2,0.8,0.2,0.1,0.5,0.6]).reshape(3,3)
W = np.array([[9,3,4],
              [2,8,2],
              [1,5,6]])*0.1
W
I = np.array([0.9,0.1,0.8]).reshape(3,1)
I
np.dot(W,I)

array([[1.16],
       [0.42],
       [0.62]])

In [230]:
W*I

array([[0.81, 0.27, 0.36],
       [0.02, 0.08, 0.02],
       [0.08, 0.4 , 0.48]])

In [272]:
e=np.random.randn(3,1)

In [273]:
W.transpose().dot(e)

array([[-0.81123053],
       [-0.74617138],
       [ 0.44341833]])

In [ ]:
#####배열의 인덱싱

In [235]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [236]:
a1[0]

0

In [237]:
a1[4]

40

In [240]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [242]:
a1[[1,3,4]]

array([10, 30, 40])

In [244]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [249]:
a2[0, 2]

30

In [250]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [254]:
a2[1]

array([40, 50, 60])

In [261]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [262]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [282]:
a2[[0, 2, 2], [0, 1, 2]]

array([10, 80, 95])

In [271]:
########배열의 슬라이싱

In [277]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [279]:
b1[:3]

array([ 0, 10, 20])

In [283]:
b1[2:]

array([20, 30, 40, 50])

In [285]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [287]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [289]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [291]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [293]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [295]:
b2[1][0:2]

array([40, 50])

In [297]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [318]:
print("arr--------------------------------------------------------------------------")
arr=np.random.randn(5,11)
print(arr)
print("answer--------------------------------------------------------------------------")
answer=arr[0:,:1]#[0:,1]로 하면 1차원 배열이기 때문에 의미가 다름. 이렇게 하면 2차원 행렬이 됨.
print(answer)
print("data--------------------------------------------------------------------------")
data=arr[0:,1:]
print(data)

arr--------------------------------------------------------------------------
[[-0.32968179  2.35061117 -1.08330875 -0.026958    1.33389875 -0.02891146
  -0.30836583  0.68923114 -1.10768982 -0.19620744  1.95882005]
 [ 0.06505215  0.69957315  1.55993187  0.21283235  1.02085424 -0.17431004
  -1.1080457  -1.34189274 -0.8427298  -0.67674342  0.90885031]
 [ 0.57111963 -0.75163556 -0.21615036  0.27060151 -0.479348    0.04192717
  -0.08826885  0.81066944 -1.86572165 -0.31523001  0.08116827]
 [-1.30303315  0.00917851 -0.96468632  1.2289882  -0.87223618  2.26266768
   0.43287156 -1.11824868  0.0416538  -1.00812933 -0.12641304]
 [-1.03797767  0.10634497  0.30964435  2.09749972  0.20886686 -0.17830989
   0.12824975  0.18097024  0.58609853 -0.87456666 -0.52912977]]
answer--------------------------------------------------------------------------
[[-0.32968179]
 [ 0.06505215]
 [ 0.57111963]
 [-1.30303315]
 [-1.03797767]]
data--------------------------------------------------------------------------


In [319]:
##############################################   판다스    pandas